language: go

go:
  - 1.8.3

install:
  - go get -u github.com/golang/lint/golint

script:
  - go generate ./...
  - go install -v ./...
  - golint ./...
  - go vet ./...
  - go test -v ./...

notifications:
 slack:
   rooms:
    secure: "JCXbAVB+2q1TWCt5amBRjkR01fiQwZsrzbZJXdCCu9AhV5g91IgyC/Tu2Qfnqy00a6SZQ1MkFUCKDjiNZS+kbRESs3rTey7ZlKx2QGNW539IxVAiii7/RSsXWThnLZQKVAU5jNdY9cL/wAiya/PUxBc/7fdeboz7emyxQbXCorwFO2T3mYHSvCMb6JYO0KUk/FipxQKpmqA9D12lXgUHKmATiKoqJkDAx0cA2Rn4QuX4WJRDbZqjXLb/rcSUgCG1Ypcbqi0nBo7sOjIrYuyZu2jhtMwhcdYOliZLadm3a7HWeZEvIa0ZW8dCOvckjSeAcFsRC/rDionbEwoTBIPCIQcMAh+Qj3rxYExwlfre+4leVk7TZt9+6xXqv+ZbxZa8RFIx6gjqczuBtPW+qd3Z2M/Sba6RwLSdjbMZDsWBLR7S3/bZR+zrkqZ+ccpYNzqUaPxF9zCZJZCZ6ULmMbEi+ES+Wl70WH8JgJPYZaqrmNkZ9y+K7/b1bKfG29RkpJSKXwopmtPHqqpIRGzC0R8hDdNlAtnGyx5jX19iSvQnOlxBFtEER25jN1d1DrPaWmjuctmKNoEbgHRGimp8UhOdqRD9VmoTHKnxpHEjrEvEaVlK75NqOxwabhhQQA2jGRG3GAIGn5ZCCbLtnLobXREHwcU9CA7JT8N2P90WFqck/Jg="
