language: go

go:
  - 1.8.3

install:
  - go get -u github.com/golang/lint/golint

script:
  - go generate ./...
  - go install -v ./...
  - golint ./...
  - go vet ./...
  - go test -v ./...

notifications:
 slack:
   rooms:
    secure: "Evku2lLcZCTgpyqNdGZ16s1LeHxIcwIyaTc4L7uatGABa4ZQnwEqPThU8HaRSfiXi+RWrJvGSqYcptGxAugXSnZCIrS9x4kWsLyT0+P/CoQdnLGOn5fvneGtVoyjnbn8HZZkxXdzb4u+7tvCLMjj0BOtlFvdjW//CCsJu7rZQO9MQNEEVsaYKaPo19j9dpgnfxE2qIcJWVRU0n0ueEztJlIRW2AAOMUnvdm1rDRCgICD5v5DcrgPy2GhtHDlt4phQIFz8CGmUP5fXJEEoLIOKmTXj/sUBQVfgITRUXg1he2AfLvnSRk6w15ucyyJnz2pXJN+qSKgbNsMV7Gp+z7K1lFibGJJeXf8sDnlJbWDHymGaontX9EaY7d5yQ7LiZFWcXR96ZSAqWYnHMCQL4tp8xOWt+JeuAjKCtqx+l5zOg/FnTM0SoMYHSZ27FJnW59epep3PgJRzVXHlc+oXjWZpVLqwf/Y7g7cq3g+yvckFuE0eVVQFjq3dejEfUvx3lFWr24kHpyYH+2Q0/vOrWO+imjCWqRdRPnPIiqMmEXdZipVhdIsO/lPgU8OtV54qNT4+Wvb3V95SH32m5XYMWgFyiSfPfIXKmKexe1ykEjypZ2uUvzfvukWIxR4f8tqhc7wC1lCA+jF4OmBXqWOhUMNA6ffZWSzERmCZIQEo5fJubE="
