language: go

go:
  - 1.8.3

install:
  - go get -u github.com/golang/lint/golint

script:
  - go generate ./...
  - go install -v ./...
  - golint ./...
  - go vet ./...
  - go test -v ./...

notifications:
 slack:
   rooms:
    - deadlockx42:APY2n5wySNi22t1AvUefBjy8#build
